### ISSUE TITLE
thanks for your work

### ISSUE THREAD

**Issue by flyinghappyking** [kemalsanli/Monster-Abra-A7-V6-Big-Sur-OC-EFI#2]
I used your EFI, it is almost perfect and I would like to say thank you!
My laptop is MSI GE60 2pl Apache, the configuration is as following:
CPU: 4710HQ
GPU: HD4600 (working) / GTX850M (disabled)
Sound card: ALC 892, LAYOUT ID （04000000）
Memory: 8GB*2
wireless net card: Intel 3160, RTL 8118
wired net card: Atheros Killer 2000.
it seemed perfect with big sur.
but there is one thing not solved, the HDMI output doesn't work. I have two connection ports: VGA and HDMI. I tried to patch it with Hackintools, but it didn't work, I first set con1 as HDMI and con2 as VGA, didn't work; then I reversed it and set con1 as vga and con2 as hdmi, didn't work. when i plug hdmi to my laptop, no output and many times it resulted to reboot the big sur.
do you have any idea about the hdmi output?
thanks again for your great work!

**Comment by kemalsanli** [comment]
No problems at all ^^

This also happened to me before framebuffer patch,

But before doing something you should check nvidia optimus, if your computer have optimus feature you cannot get output from hdmi on macos. For testing this on windows you need to disable your nvidia card and check hdmi ports, if you can get output from hdmi this means you probably can get output in macOS too but if you are not there is no possible way to use hdmi.

if you get output while nvidia card disabled

remove framebuffer patches and try all this id's without framebuffer patch

![Ekran Resmi 2021-01-25 04 31 43](https://user-images.githubusercontent.com/22424289/105650882-3de6bf00-5ec6-11eb-8072-999fef6590cd.png)

when you find a id that working no issues start to patch framebuffer, also try every id because sometime hackintool show mobile not supported but id works on mobile.

You can use this to patch frame buffer.
https://www.tonymacx86.com/threads/guide-general-framebuffer-patching-guide-hdmi-black-screen-problem.269149/
